# Generated by Django 2.2.13 on 2020-06-08 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='posted_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
